Update autocomment-pr-raise.yml
Appended the auto-commenting feature for issues raised

diff --git a/.github/workflows/autocomment-pr-raise.yml b/.github/workflows/autocomment-pr-raise.yml
--- a/.github/workflows/autocomment-pr-raise.yml
+++ b/.github/workflows/autocomment-pr-raise.yml
@@ -1,7 +1,9 @@
-name: Auto Comment on PR
+name: Auto Comment on PR and Issue
 
 on:
   pull_request_target:
+    types: [opened]
+  issues:
     types: [opened]
 
 permissions:
@@ -9,8 +11,9 @@ permissions:
   pull-requests: write
 
 jobs:
-  comment:
+  comment-pr:
     runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request_target'
 
     steps:
     - name: Add Comment to Pull Request
@@ -26,6 +29,33 @@ jobs:
           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
+          -d "$COMMENT")
+        cat response.json
+        if [ "$RESPONSE" -ne 201 ]; then
+          echo "Failed to add comment"
+          exit 1
+        fi
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  comment-issue:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'issues'
+
+    steps:
+    - name: Add Comment to Issue
+      run: |
+        COMMENT=$(cat <<EOF
+        {
+          "body": "[Auto-Comment]: Thank you for raising this issue! 🚀 We've received your input and will review it shortly. Please make sure to check our CONTRIBUTING.md for any additional information. Feel free to reach out if you have any questions or need further assistance. Happy contributing! 😊"
+        }
+        EOF
+        )
+        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
+          -X POST \
+          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
           -d "$COMMENT")
         cat response.json
         if [ "$RESPONSE" -ne 201 ]; then
